language: cpp

matrix:
  include:
  - os: osx
    compiler: clang
    env: EXTRA_CMAKE_FLAGS="-DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_MACOSX_RPATH=ON" CMAKE_BUILD_TYPE=Release BUILD_SHARED_LIBS=ON
  - os: linux
    compiler: gcc
    env: CMAKE_BUILD_TYPE=Release BUILD_SHARED_LIBS=ON
  - os: linux
    compiler: clang
    env: CMAKE_BUILD_TYPE=Release BUILD_SHARED_LIBS=ON
  - os: linux
    compiler: gcc
    env: CMAKE_BUILD_TYPE=Debug BUILD_SHARED_LIBS=ON
  - os: linux
    compiler: gcc
    env: CMAKE_BUILD_TYPE=Release BUILD_SHARED_LIBS=OFF
  - os: linux
    compiler: gcc
    env: CMAKE_BUILD_TYPE=Debug BUILD_SHARED_LIBS=OFF

before_install:
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew tap homebrew/science; else sudo apt-get update -qq; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openblas; else sudo apt-get install -qq libblas-dev; fi

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DBUILD_EXAMPLES=ON -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE $EXTRA_CMAKE_FLAGS ..
  - make VERBOSE=1
